### ISSUE TITLE
error: could not create '/usr/local/lib/python3.6/dist-packages/lios': Permission denied

### ISSUE THREAD

**Issue by mozgbrasil** [zendalona/lios#12]
Hello, good morning my friends

@Nalin-x-Linux @LAfricain @balazsszalab 

Can you help me with this occurrence, I am following the installation process as images

![Captura de tela de 2020-01-17 13-17-51](https://user-images.githubusercontent.com/17202780/72628712-a4d5ad80-392d-11ea-814b-6998062eb521.png)
![Captura de tela de 2020-01-17 13-18-01](https://user-images.githubusercontent.com/17202780/72628714-a56e4400-392d-11ea-92d8-055917ef05e4.png)

**Comment by cibersheep** [comment]
I think you are trying to install LIOS in `/usr` without `sudo`. That's why the permissions error

**Comment by mozgbrasil** [comment]
@cibersheep 

Hello

In the documentation on

https://github.com/Nalin-x-Linux/lios-3#installing

We don't see the instruction to use "sudo"

I also see in some posts that the use of "sudo" is not recommended

Maybe I should apply some support in my environment I will search further, thanks anyway

**Comment by LAfricain** [comment]
You can use my [ppa](https://launchpad.net/~lafricain79/+archive/ubuntu/lafricainenvrac), it's easier. And on [gitlab](https://gitlab.com/Nalin-x-Linux/lios-3) you have more activities. If you want to translate it in Spanish, it would be great! I can add it to my deb on the ppa.

**Comment by mozgbrasil** [comment]
Hello

@LAfricain 

I managed to install lios via ppa

I live in Brazil and my fluent language is Portuguese from Brazil

I can translate into my language

I already have this repository on gitlab

https://gitlab.com/mozgbrasil

And I have this account on the launchpad

https://launchpad.net/~mozgbrasil




![Captura de tela de 2020-01-17 18-43-32](https://user-images.githubusercontent.com/17202780/72649533-b4b8b600-395c-11ea-8a79-ed9871870452.png)
![Captura de tela de 2020-01-17 18-47-51](https://user-images.githubusercontent.com/17202780/72649534-b4b8b600-395c-11ea-9e22-6751f65930ef.png)

**Comment by cibersheep** [comment]
> @cibersheep
[...]
> In the documentation on
> https://github.com/Nalin-x-Linux/lios-3#installing

You might tell to the installer that the target is in your user folder tree

`python3 setup.py install --install-data=~/[some/folder/under/documents]` the `~` indicates home folder. Just need to replace [some/folder/under/documents] for a folder you have in your home

> I also see in some posts that the use of "sudo" is not recommended
True, normally is not recommended. I was pointing I think was the error. Trying to install in a system folder (`/usr`) without sudo privileges :)

**Comment by LAfricain** [comment]
> I already have this repository on gitlab

Okay, then just fork the [master LIOS branch](https://gitlab.com/Nalin-x-Linux/lios-3) on gitlab,clone it in your computer, and create a new pt_BR.po file in the po folder, and translate it. After ask for a merge request. I will add it to the launchpad package.
I just [open a ticket on gitlab](https://gitlab.com/Nalin-x-Linux/lios-3/issues/22). We can work on it together if you have questions
