### ISSUE TITLE
index error main.py

### ISSUE THREAD

**Issue by BASIC1978** [zendalona/lios#19]
Mint cinnamon 64bit fresh install.
Lios install from git-clone
Tesseract w/ train from git-clone

Getting index error line 1327 lang = languages[self.preferences.language]
What to do?

Also getting Gtk warning cannot connect attribute "text" ... Does not exist.

One more thing. All dependencies are satisfied save one. Python3 imaging sane. Can't find it anywhere. Is this a problem? Thanks.

**Comment by Nalin-x-Linux** [comment]
Installed Tesseract language data ?

**Comment by BASIC1978** [comment]
Found language data. Thanks much. Sorry for the trouble.
